Sort Queues by rates
cloudamqp/lavinmq pull request #367
Opened 2022-07-21 12:11 UTC by Christina-84

This update allows users to sort queues by message rates. 
It also adds Redelivery rate to the queues table, and lets users sort by redelivery rate as well. 

#342 
![sort_by_rates](https://user-images.githubusercontent.com/85930202/180210473-bded3997-59ac-4b4f-bf5d-28a9aeddc209.png)

2022-08-02 13:33 UTC, jage commented
"Docker images / main (pull_request)" is failing due to credentials being ignored since you were not a collaborator on this repo when the PR was opened. I've added you and tried to rerun but still fails, so let's just ignore it here as it will (most likely) work next time.

2022-08-02 14:31 UTC, jage commented
Did some experiment and found a weird behaviour.

3 queues with some traffic, sorting on delivery rate and expected the paused queue to be at the bottom, but it's in the middle? 😄 
Not sure if it's related to how rates are updated (auto-refresh) or if it's something else but maybe we can try to debug this now that we're looking at sorting. 

![Screenshot 2022-08-02 at 16 29 12](https://user-images.githubusercontent.com/7913/182399676-9cc0f849-4145-472d-9752-68e05d73ea05.png)

2022-08-16 11:28 UTC, carlhoerberg approved these changes

2022-08-16 11:30 UTC, carlhoerberg requested changes
oh, yeah, it's not as easy as just to add the `data-sort-key` attribute, those attributes have to map to something, and there's no `publish` property on the `item`

2022-08-17 14:32 UTC, Christina-84 commented
We now sort by rates in queues, but would like to write more dynamic code as it is currently hardcoded to work for message_stats

2022-08-17 23:55 UTC, carlhoerberg commented
Fixed the dynamic sorting. Wrote a custom `dig` that always returns a `NamedTuple` except for the last sort key

2022-08-18 18:59 UTC, merged