Streams - keep track of first offset per segment
cloudamqp/lavinmq pull request #817
Opened 2024-10-25 13:51 UTC by viktorerlingsson

### WHAT is this pull request doing?
Saves a hash with the first offset for each segment, greatly reducing the time (and memory used) to find a message by offset. 

Tests done by getting a message by a random offset 10 times in a stream with 10M messages. 

main: 
```
Getting 10 messages by random offsets...
Average time: 660.8 milliseconds
Maximum resident set size (kbytes): 824424
```

this branch: 
```
Getting 10 messages by random offsets...
Average time: 52.9 milliseconds
Maximum resident set size (kbytes): 23692
```

### HOW can this pull request be tested?
Existing specs in `stream_queue_spec.cr` should cover this pretty well.

2024-10-25 15:13 UTC, spuun commented
Cool!
Maybe a sorted array could perform even better since that would enable binary search. Store tuples of `{UInt32, Int64}`.
Which makes me wonder... Will the keys in the Hash always be sorted? I.e. are they always inserted sorted?

2024-10-26 07:40 UTC, viktorerlingsson commented
> Maybe a sorted array could perform even better since that would enable binary search. Store tuples of `{UInt32, Int64}`. Which makes me wonder... Will the keys in the Hash always be sorted? I.e. are they always inserted sorted?

Yeah, probably! I don't think it will make a huge difference, since the number of segments won't be super big. But can give it a try 👍 

Yes, it should always be sorted. We only add larger offsets and delete the smallest.

2024-10-26 23:38 UTC, carlhoerberg reviewed
Good feature!

Could theoretically build an index over timestamps too, right?

2024-10-26 23:38 UTC, carlhoerberg commented on src/lavinmq/queue/stream_queue_message_store.cr
> +      private def find_first_offset_per_segment
```suggestion
      private def build_segment_offset_index
```

2024-10-26 23:38 UTC, carlhoerberg commented on src/lavinmq/queue/stream_queue_message_store.cr
> +      @first_offset_per_segment = Hash(UInt32, Int64).new
better naming?
```suggestion
      @offset_index = Hash(UInt32, Int64).new # segment_id => offset of first msg
```
or 
```suggestion
      @segment_first_index = Hash(UInt32, Int64).new
```

2024-10-26 23:38 UTC, carlhoerberg commented on src/lavinmq/queue/stream_queue_message_store.cr
> +        end
I would create the new hash here and return it in the constuctor:

```suggestion
        @segments.transform_values do |seg_id, mfile|
          msg = BytesMessage.from_bytes(mfile.to_slice + 4u32)
          offset_from_headers(msg.properties.headers)
        end
```

2024-10-26 23:38 UTC, carlhoerberg commented on src/lavinmq/queue/stream_queue_message_store.cr
> +      private def find_segment_by_offset(offset) : UInt32
```suggestion
      private def offset_index_lookup(offset) : UInt32
```

2024-11-11 11:54 UTC, carlhoerberg requested changes

2024-11-11 11:54 UTC, carlhoerberg commented on src/lavinmq/amqp/queue/stream_queue_message_store.cr
> +      @offset_index_ts : Hash(UInt32, Int64)           # segment_id => ts of first msg
better name that describes the property better? 
```suggestion
      @timestamp_index : Hash(UInt32, Int64)           # segment_id => ts of first msg
```

2024-11-11 11:54 UTC, carlhoerberg commented on src/lavinmq/amqp/queue/stream_queue_message_store.cr
> +            break if first_seg_offset >= offset
if `first_seg_offset` matches the searched for offset we should give that segment, not the full previous segment, right? 
```suggestion
            break if first_seg_offset > offset
```

2024-11-11 11:54 UTC, carlhoerberg commented on src/lavinmq/amqp/queue/stream_queue_message_store.cr
> +            break if Time.unix_ms(first_seg_ts) >= offset
```suggestion
            break if Time.unix_ms(first_seg_ts) > offset
```

2024-11-11 11:54 UTC, carlhoerberg commented on src/lavinmq/amqp/queue/stream_queue_message_store.cr
> +          @offset_index[@segments.last_key] = @last_offset
is `@last_offset` really correct here? or is it `@last_offset + 1` that will be written as the first offset to the new segment? 
```suggestion
          @offset_index[@segments.last_key] = @last_offset
```

2024-11-11 11:54 UTC, carlhoerberg commented on src/lavinmq/amqp/queue/stream_queue_message_store.cr
> +          @offset_index[@segments.last_key] = @last_offset
what about `@timestamp_index`? It isn't updated?

2024-11-11 11:54 UTC, carlhoerberg commented on src/lavinmq/amqp/queue/stream_queue_message_store.cr
> +          @offset_index.delete(seg_id)
```suggestion
          @offset_index.delete(seg_id)
          @timestamp_index.delete(seg_id)
```

2024-11-11 11:54 UTC, carlhoerberg commented on src/lavinmq/amqp/queue/stream_queue_message_store.cr
> +      end
Build both indexes at the same time? Now we have to read all segments twice.

2024-11-13 08:22 UTC, merged