Streams filters
cloudamqp/lavinmq pull request #893
Opened 2024-12-18 15:06 UTC by viktorerlingsson

### WHAT is this pull request doing?
Adds support for filtering in streams

### HOW can this pull request be tested?
Run specs

2025-01-09 13:45 UTC, spuun commented on src/lavinmq/amqp/stream_consumer.cr
> +          @filter = frame.arguments["x-stream-filter-value"].to_s
What about
```suggestion
          @filter = frame.arguments["x-stream-filter-value"].to_s.split(",")
```
to get rid of the `split` in `StreamQueueMessageStore#matching?`? That would get rid of some allocations for every call to `#matching?`.

2025-01-09 13:54 UTC, spuun reviewed
See inline comments.

2025-01-09 16:05 UTC, viktorerlingsson commented on src/lavinmq/amqp/queue/stream_queue_message_store.cr
> +        if filter = headers.not_nil!("Message lacks headers")["x-stream-filter-value"]?
Yeah, looks better, thanks! 👍

2025-01-09 16:06 UTC, viktorerlingsson commented on src/lavinmq/amqp/stream_consumer.cr
> +          @filter = frame.arguments["x-stream-filter-value"].to_s
Yes, that's better 👍

2025-01-10 07:52 UTC, spuun approved these changes

2025-01-10 07:52 UTC, spuun commented on src/lavinmq/amqp/queue/stream_queue_message_store.cr
> +          end
```suggestion
            return consumer_filter.includes? msg_filter
```

2025-01-10 07:52 UTC, spuun commented on src/lavinmq/amqp/queue/stream_queue_message_store.cr
> +          if consumer_filter = consumer.filter # can be a string or an array of comma-separated strings
Always an array now. Probably no need to explain it anymore?
```suggestion
          if consumer_filter = consumer.filter
```

2025-01-10 07:52 UTC, spuun commented on src/lavinmq/amqp/queue/stream_queue_message_store.cr
> +        false
With the above change this is never reached
```suggestion
```

2025-01-10 07:52 UTC, spuun commented on src/lavinmq/amqp/stream_consumer.cr
> +        when Nil
At first I managed to interpret the code to raise on nil.
```suggestion
        when Nil
          # nop
```

2025-01-10 07:52 UTC, spuun commented on src/lavinmq/amqp/stream_consumer.cr
> +        when Nil
```suggestion
        when Nil
          # nop
```

2025-01-19 23:25 UTC, carlhoerberg requested changes

2025-01-19 23:25 UTC, carlhoerberg commented on src/lavinmq/amqp/stream_consumer.cr
> +          @filter = frame.arguments["x-stream-filter-value"].to_s.split(",")
by sorting the filter bsearch could be used to find matches faster. 
```suggestion
        case filter = frame.arguments["x-stream-filter-value"]?
        when String
          @filter = filter.split(',').sort!
```

2025-01-19 23:25 UTC, carlhoerberg commented on src/lavinmq/amqp/queue/stream_queue_message_store.cr
> +      end
```suggestion
      private def filter_value_from_headers(headers) : String?
        headers.try &.fetch("x-stream-filter-value", nil).try &.to_s
      end
```

2025-01-19 23:25 UTC, carlhoerberg commented on src/lavinmq/amqp/queue/stream_queue_message_store.cr
> +      end
Or maybe this is more readable? 
```suggestion
      private def filter_value_from_headers(headers : Hash) : String?
        if value = headers["x-stream-filter-value"]?
          value.to_s
        end
      end
      
      private def filter_value_from_headers(headers : Nil) : Nil
      end
```

2025-01-19 23:25 UTC, carlhoerberg commented on src/lavinmq/amqp/queue/stream_queue_message_store.cr
> +          return consumer_filter.includes? msg_filter
Could be speed up with bsearch (just have to make sure filters array is sorted). 
```suggestion
        if filter_value = filter_value_from_headers(msg_headers)
          return consumer_filter.bsearch { |f| f >= filter_value } == filter_value
```

2025-01-19 23:25 UTC, carlhoerberg commented on src/lavinmq/amqp/queue/stream_queue_message_store.cr
> +          end
I think it would be nicer to move this to the consumer. Then the consumer doesn't need to make `filter` and `match_unfiltered` public. 
```suggestion
          return unless consumer.filter_match?(msg.properties.headers)
```

2025-01-20 09:34 UTC, viktorerlingsson commented on src/lavinmq/amqp/queue/stream_queue_message_store.cr
> +      end
I think the first suggestion is readable enough!

2025-01-20 10:32 UTC, carlhoerberg commented on src/lavinmq/amqp/stream_consumer.cr
> +      @filter : Array(String)? = nil
My last question is, should the filter be an empty array by default? Then  `filter_match?` could return early with `return true if @filter.empty?

2025-01-20 23:20 UTC, carlhoerberg approved these changes

2025-01-20 23:20 UTC, carlhoerberg commented on src/lavinmq/amqp/stream_consumer.cr
> +      @match_unfiltered : Bool = false
```suggestion
      @filter = Array(String).new
      @match_unfiltered = false
```

2025-01-23 10:53 UTC, merged